Duskhaven-Reforged/DuskForgedCore

modules/mod-Forge/src/CommandHandlers/ForgeCacheCommands.cpp, modules/mod-Forge/src/ForgeCache.cpp, modules/mod-Forge/src/ForgeCommonMessage.cpp, modules/mod-Forge/src/ForgeCommonMessage.h, modules/mod-Forge/src/ForgePlayerMessageHandler.cpp, modules/mod-Forge/src/TopicHandlers/LearnTalentHandler.cpp, modules/mod-Forge/src/TopicHandlers/UnlearnTalentHandler.cpp, src/server/game/Entities/Creature/Creature.cpp, src/server/game/Entities/Creature/CreatureOutfit.h, src/server/game/Entities/Player/PlayerUpdates.cpp, src/server/game/Globals/ObjectMgr.cpp, src/server/game/Maps/Map.cpp, src/server/game/Maps/Map.h, src/server/game/Spells/Auras/SpellAuraEffects.cpp, src/server/scripts/Commands/cs_reload.cpp
=> Hateforge stuff :)

src/server/scripts/Spells/spell_hunter.cpp
=> kill command script

src/server/game/Entities/Player/PlayerQuest.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Handlers/LootHandler.cpp, src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp, src/server/game/Spells/Auras/SpellAuraDefines.h, src/server/game/Spells/Auras/SpellAuraEffects.cpp, src/server/game/Spells/Spell.h, src/server/game/Spells/SpellEffects.cpp, src/server/shared/DataStores/DBCStructure.h, src/server/shared/SharedDefines.h
Auras: SPELL_AURA_MOD_SCHOOL_MASK_HEALING_FROM_CASTER, SPELL_AURA_MOD_MONEY_GAIN, SPELL_AURA_MOD_TAXI_FLIGHT_SPEED.
Effects: SPELL_EFFECT_RESTORE_SPELL_CHARGE, SPELL_EFFECT_GIVE_EXPERIENCE, SPELL_EFFECT_GIVE_RESTED_EXPERIENCE_BONUS, SPELL_EFFECT_GIVE_HONOR, SPELL_EFFECT_RECEIVE_ITEM.
Refer to either code or dev flag spreadsheet.
=> Spell auras and effects

modules/mod-Forge/src/ForgeCache.cpp, modules/mod-Forge/src/ForgePlayerMessageHandler.cpp
=> add default loadouts

modules/mod-Forge/src/ForgeCache.cpp
=> add map for default spec

modules/mod-Forge/src/ForgeCache.cpp
=> update cache for defaults

modules/mod-Forge/src/TopicHandlers/DeleteLoadoutHandler.cpp
=> update id to disallow default delete

data/sql/custom/db_world/20240114_01.sql
=> add action sql

modules/mod-Forge/src/ForgeCache.cpp, modules/mod-Forge/src/ForgePlayerMessageHandler.cpp, modules/mod-Forge/src/TopicHandlers/LearnTalentHandler.cpp, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h, src/server/game/Entities/Player/PlayerStorage.cpp, src/server/game/Handlers/MiscHandler.cpp
=> fix actions

data/sql/custom/db_world/20231226 forge_character_talent_loadouts.sql, data/sql/custom/db_world/20240118_01.sql, modules/mod-Forge/src/ForgePlayerMessageHandler.cpp
=> fix table def

data/sql/custom/db_world/20230918_01.sql
=> tmog tables

data/sql/custom/db_characters/20230918_01.sql
=> move file to right folder

data/sql/custom/db_characters/20230918_01.sql
=> im retarded

src/server/game/Entities/Player/PlayerUpdates.cpp, src/server/game/Maps/Map.cpp
=> threat mgr update

src/server/game/Entities/Unit/Unit.cpp
=> woops; forgot to add this line

src/server/game/Combat/CombatManager.cpp, src/server/game/Combat/CombatManager.h
=> add check function for threat mgr

src/server/game/Combat/CombatManager.cpp, src/server/game/Combat/CombatManager.h
=> add pve threat refresh function

src/server/game/Combat/CombatManager.cpp, src/server/game/Combat/CombatManager.h
=> fix suppression inheritance

src/server/game/Combat/CombatManager.cpp, src/server/game/Combat/CombatManager.h
=> move functions around

data/sql/custom/db_world/20240221_01.sql
=> fix worldlocs

src/server/game/Entities/Player/Player.h, src/server/game/Entities/Player/PlayerStorage.cpp, src/server/game/Guilds/Guild.cpp, src/server/game/Handlers/MailHandler.cpp
=> Tidy up core methods
